services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loginapp
    volumes:
      - ./handle database.sql:/docker-entrypoint-initdb.d/handle database.sql
      - ./mysql_data:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s

  flaskapp:
    build:
      context: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: logindb
    depends_on:
      - mysql
    networks:
      - twotier
    restart: always


networks:
  twotier: