name: CI Pipeline for Building the Docker Image
# github actions event
on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: my-ubuntu
    steps:
      - run: echo "This is my first step!!"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lets build the image"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8' 
      - run: |
          pip install -r requirements.txt
          FLASK_APP=main.py FLASK_DEBUG=1 FLASK_ENV=development flask run