name: CI Pipeline for Building the Docker Image
# github actions event
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: my-ubuntu
    steps:
      - run: echo "Lets build the image"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          docker: 'latest' 
      - run: |
              docker --version
              